"""update_users_table_for_registration

Revision ID: fdcd923df5ec
Revises: 88a289086b7a
Create Date: 2025-12-28 23:41:04.841581

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fdcd923df5ec"
down_revision: Union[str, Sequence[str], None] = "88a289086b7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала добавляем новые колонки как nullable
    op.add_column(
        "users", sa.Column("telegram_id", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "users", sa.Column("pachca_id", sa.String(length=100), nullable=True)
    )
    
    # Устанавливаем значения по умолчанию для существующих записей (если есть)
    op.execute("UPDATE users SET telegram_id = 'default' WHERE telegram_id IS NULL")
    op.execute("UPDATE users SET pachca_id = 'default' WHERE pachca_id IS NULL")
    op.execute("UPDATE users SET first_name = 'Unknown' WHERE first_name IS NULL")
    op.execute("UPDATE users SET last_name = 'Unknown' WHERE last_name IS NULL")
    
    # Теперь делаем колонки NOT NULL
    op.alter_column(
        "users", "telegram_id", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "users", "pachca_id", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "users", "first_name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "users", "last_name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users", "last_name", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "users", "first_name", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_column("users", "pachca_id")
    op.drop_column("users", "telegram_id")
    # ### end Alembic commands ###
