"""make_user_fields_optional_except_email

Revision ID: aff4a2463ebf
Revises: fdcd923df5ec
Create Date: 2025-12-28 23:53:10.340656

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aff4a2463ebf"
down_revision: Union[str, Sequence[str], None] = "fdcd923df5ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "first_name", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "users", "last_name", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "users", "telegram_id", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "users", "pachca_id", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "pachca_id", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "users", "telegram_id", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "users", "last_name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "users", "first_name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    # ### end Alembic commands ###
