apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email для уведомлений о сертификатах (ЗАМЕНИТЕ на ваш email)
    email: arsen.davydov@gmail.com
    # Хранилище для приватного ключа
    privateKeySecretRef:
      name: letsencrypt-prod
    # Метод проверки домена (HTTP-01 challenge)
    solvers:
    - http01:
        ingress:
          class: nginx
---
# Для тестирования (staging) - используйте сначала этот, потом переключитесь на prod
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: arsen.davydov@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx

